services:
  scrapers:
    build: ./scrapers
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  nextjs:
    build: ./next-app
#      context: ./next-app
#      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next-app:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
